# Generated by Django 5.1.5 on 2025-01-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=50)),
                ('service_id', models.CharField(max_length=50)),
                ('route_id', models.CharField(max_length=50)),
                ('trip_headsign', models.CharField(max_length=50)),
                ('shape_id', models.CharField(max_length=50)),
            ],
        ),
    ]
