# Generated by Django 5.1.5 on 2025-01-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrobus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='id',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='trip_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
