# Generated by Django 5.1.5 on 2025-01-24 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrobus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='id_shape',
            new_name='shape',
        ),
    ]
